Support regx exclude interface list
wobcom/transceiver-exporter pull request #4
Opened 2022-10-14 08:16 UTC by XuHandsome

### fix: To solve character encoding error in driver version return
some network interface return driver version
Maybe the country of manufacturer, the character "\x00" in driver version response, it leads the metrics pages context-Type change to "binary", like this:
```bash
transceiver_driver_version_info{driver_version="1.0.0\\x00-50-generic",interface="enp0s5"} 1
transceiver_driver_version_info{driver_version="1.0\\x00.0-50-generic",interface="cali2d8e0dfad7a"} 1
transceiver_driver_version_info{driver_version="1.0\\x00.0-50-generic",interface="calib073cd807d5"} 1
transceiver_driver_version_info{driver_version="1.0\\x00.0-50-generic",interface="calidf4d15675a8"} 1
transceiver_driver_version_info{driver_version="1.0\\x00.0-50-generic",interface="calif0538e521e7"} 1
transceiver_driver_version_info{driver_version="2.3\\x00.0-50-generic",interface="docker0"} 1
transceiver_driver_version_info{driver_version="5.15.0-50-generic",interface="kube-ipvs0"} 1
```

### feat: support regx exclude interface list
In virtualized operating system, like installed docker proxmox and other, so much virtual bridge device, like `docker0` `docker1` `bond0` `bond1` `vmbr0v5050` `vmbr1v3000` and other, so i added the regx support, just with the `-exclude.interfaces` parameter, same as before.
```bash
./transceiver-exporter -exclude.interfaces bond*,vmbr*,tap*,docker*,eth0
```

2022-10-14 16:05 UTC, vidister commented
Hi, thanks for contributing. Looks good to me, I will run some tests, add some documentation and create a release then.

2023-06-14 13:52 UTC, johannwagner commented
Actually, your proposed syntax is not regex but some type of Linux globs but your proposed code does actual regex matching. I would also like to introduce a feature switch to enable Regex support to ensure a non-breaking new version.

2023-06-14 14:05 UTC, johannwagner requested changes

2023-06-14 14:05 UTC, johannwagner commented on main.go
> +	excludeInterfaces        = flag.String("exclude.interfaces", "", "Comma seperated list of interfaces regular to exclude")
Please introduce a seperate feature switch to enable Regex matching

2023-06-14 14:05 UTC, johannwagner commented on transceiver-collector/util.go
> +func quoteToascii(str string) string {
`quoteToASCII`

2023-06-14 14:05 UTC, johannwagner commented on main.go
> +	if len(*excludeInterfaces) != 0 {
Since we got new features, it would also be nice to support regex for included interfaces.

2023-11-24 14:18 UTC, vidister commented
superseded by #9 

nevertheless, thank you for your contribution.

2023-11-24 14:18 UTC, closed without merging